services:
  backend-flask:
    environment:
      CONNECTION_URL: "${PROD_CONNECTION_URL}"
      FRONTEND_URL: "https://${CODESPACE_NAME}-3000.${GITHUB_CODESPACES_PORT_FORWARDING_DOMAIN}"
      BACKEND_URL: "https://${CODESPACE_NAME}-4567.${GITHUB_CODESPACES_PORT_FORWARDING_DOMAIN}"
      # OTEL_SERVICE_NAME: 'backend-flask'
      # OTEL_EXPORTER_OTLP_ENDPOINT: "https://api.honeycomb.io"
      # OTEL_EXPORTER_OTLP_HEADERS: "x-honeycomb-team=${HONEYCOMB_API_KEY}"
      AWS_DEFAULT_REGION: "${AWS_DEFAULT_REGION}"
      AWS_ACCESS_KEY_ID: "${AWS_ACCESS_KEY_ID}"
      AWS_SECRET_ACCESS_KEY: "${AWS_SECRET_ACCESS_KEY}"
      AWS_COGNITO_USER_POOL_ID: "us-east-1_019cAtPHi"
      AWS_COGNITO_USER_POOL_CLIENT_ID: "6bdss0f1867al22lee8jd3duku"   
    build: ./backend-flask
    ports:
      - "4567:4567"

  frontend-react-js:
    environment:
      REACT_APP_BACKEND_URL: "https://${CODESPACE_NAME}-4567.${GITHUB_CODESPACES_PORT_FORWARDING_DOMAIN}"
      REACT_APP_AWS_PROJECT_REGION: "${AWS_DEFAULT_REGION}"
      REACT_APP_AWS_COGNITO_REGION: "${AWS_DEFAULT_REGION}"
      REACT_APP_AWS_USER_POOLS_ID: "us-east-1_019cAtPHi"
      REACT_APP_CLIENT_ID: "6bdss0f1867al22lee8jd3duku"
    build: ./frontend-react-js
    ports:
      - "3000:3000"
    # volumes: # chatgpt recommended to get rid of the volume so that  Docker installs node_modules inside the container
 
    #   - ./frontend-react-js:/frontend-react-js
  db:
    image: postgres:16-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    ports:
      - '5432:5432'
    volumes: 
      - db:/var/lib/postgresql/data

# the name flag is a hack to change the default prepend folder
# name when outputting the image names
networks: 
  internal-network:
    driver: bridge
    name: cruddur
volumes:
  db:
    driver: local