services:
  backend-flask:    # service name
    environment:
      # AWS_ENDPOINT_URL: "http://dynamodb-local:8000"
      CONNECTION_URL: "${PROD_CONNECTION_URL}"
      # CONNECTION_URL: "postgresql://postgres:password@db:5432/cruddur"
      FRONTEND_URL: "https://${CODESPACE_NAME}-3000.${GITHUB_CODESPACES_PORT_FORWARDING_DOMAIN}"
      BACKEND_URL: "https://${CODESPACE_NAME}-4567.${GITHUB_CODESPACES_PORT_FORWARDING_DOMAIN}"
      # OTEL_SERVICE_NAME: 'backend-flask'
      # OTEL_EXPORTER_OTLP_ENDPOINT: "https://api.honeycomb.io"
      # OTEL_EXPORTER_OTLP_HEADERS: "x-honeycomb-team=${HONEYCOMB_API_KEY}"
      AWS_DEFAULT_REGION: "${AWS_DEFAULT_REGION}"
      AWS_ACCESS_KEY_ID: "${AWS_ACCESS_KEY_ID}"
      AWS_SECRET_ACCESS_KEY: "${AWS_SECRET_ACCESS_KEY}"
      AWS_COGNITO_USER_POOL_ID: "${AWS_COGNITO_USER_POOL_ID}"
      AWS_COGNITO_USER_POOL_CLIENT_ID: "6bdss0f1867al22lee8jd3duku"   
    build: ./backend-flask
    ports:
      - "4567:4567"

  frontend-react-js:    # service name
    environment:
      REACT_APP_BACKEND_URL: "https://${CODESPACE_NAME}-4567.${GITHUB_CODESPACES_PORT_FORWARDING_DOMAIN}"
      REACT_APP_AWS_PROJECT_REGION: "${AWS_DEFAULT_REGION}"
      REACT_APP_AWS_COGNITO_REGION: "${AWS_DEFAULT_REGION}"
      REACT_APP_AWS_USER_POOLS_ID: "us-east-1_019cAtPHi"
      REACT_APP_CLIENT_ID: "6bdss0f1867al22lee8jd3duku"
    build: ./frontend-react-js
    ports:
      - "3000:3000"
    # volumes: # chatgpt recommended to get rid of the volume so that  Docker installs node_modules inside the container
 
    #   - ./frontend-react-js:/frontend-react-js
  dynamodb-local:    # service name
    # https://stackoverflow.com/questions/67533058/persist-local-dynamodb-data-in-volumes-lack-permission-unable-to-open-databa
    # We needed to add user:root to get this working.
    user: root
    command: "-jar DynamoDBLocal.jar -sharedDb -dbPath ./data"
    image: "amazon/dynamodb-local:latest"
    container_name: dynamodb-local
    ports:
      - "8000:8000"
    volumes:
      - "./docker/dynamodb:/home/dynamodblocal/data"
    working_dir: /home/dynamodblocal
  db:      # service name
    image: postgres:16-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    ports:
      - '5432:5432'
    volumes: 
      - db:/var/lib/postgresql/data

# the name flag is a hack to change the default prepend folder
# name when outputting the image names
networks:     # service name
  internal-network:
    driver: bridge
    name: cruddur
volumes:
  db:
    driver: local